### ISSUE TITLE
android 真机编译失败

### ISSUE THREAD

**Issue by CZ2019518** [andfaraway/flutter_wxwork#1]
/Users/chengzhang/Downloads/project/zx/numerical-app/app/build/flutter_wxwork/generated/source/buildConfig/debug/com/example/flutter_wxwork/BuildConfig.java:6: 错误: 无法访问java.lang
public final class BuildConfig {
             ^
  ZipException opening "jetified-flutter_embedding_debug-1.0.0-767d8c75e898091b925519803830fc2721658d07.jar": zip END header not found
/Users/chengzhang/Downloads/project/zx/numerical-app/app/build/flutter_wxwork/generated/source/buildConfig/debug/com/example/flutter_wxwork/BuildConfig.java:8: 错误: 找不到符号
  public static final String LIBRARY_PACKAGE_NAME = "com.example.flutter_wxwork";
                      ^
  符号:   类 String
  位置: 类 BuildConfig
/Users/chengzhang/Downloads/project/zx/numerical-app/app/build/flutter_wxwork/generated/source/buildConfig/debug/com/example/flutter_wxwork/BuildConfig.java:9: 错误: 找不到符号
  public static final String BUILD_TYPE = "debug";
                      ^

**Comment by andfaraway** [comment]
我刚测试过了，真机是可以的，没有出现这种情况。你可以尝试清除缓存、flutter clean，若还是不行得话，你可以提供下真机的型号，运行版本以及flutter版本
