### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by almightyYantao** [andfaraway/flutter_wxwork#10]
/Users/yantao/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.4/android/src/main/java/com/example/flutter_wxwork/FlutterWxworkPlugin.java:102: 错误: 找不到符号
                ApplicationInfo info = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
                ^
  符号:   类 ApplicationInfo
  位置: 类 FlutterWxworkPlugin
/Users/yantao/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.4/android/src/main/java/com/example/flutter_wxwork/FlutterWxworkPlugin.java:102: 错误: 找不到符号
                ApplicationInfo info = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
                                                                                          ^
  符号:   变量 PackageManager
  位置: 类 FlutterWxworkPlugin
/Users/yantao/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.4/android/src/main/java/com/example/flutter_wxwork/FlutterWxworkPlugin.java:109: 错误: 找不到符号
                if (!TextUtils.isEmpty(arguments.get("type"))) {
                     ^
  符号:   变量 TextUtils
  位置: 类 FlutterWxworkPlugin
/Users/yantao/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.4/android/src/main/java/com/example/flutter_wxwork/FlutterWxworkPlugin.java:113: 错误: 找不到符号
                            WWMediaText txt = new WWMediaText(arguments.get("text"));
                            ^
  符号:   类 WWMediaText
  位置: 类 FlutterWxworkPlugin
/Users/yantao/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.4/android/src/main/java/com/example/flutter_wxwork/FlutterWxworkPlugin.java:113: 错误: 找不到符号
                            WWMediaText txt = new WWMediaText(arguments.get("text"));

**Comment by almightyYantao** [comment]
只要在pubspec里面加了：  flutter_wxwork: ^0.0.4
就会编译报错，还需要在哪里做配置吗？

**Comment by andfaraway** [comment]
> 只要在pubspec里面加了： flutter_wxwork: ^0.0.4 就会编译报错，还需要在哪里做配置吗？

腾讯的sdk只支持真机,模拟器编译不了

**Comment by almightyYantao** [comment]
我修改了下FlutterWxworkPlugin.java里面的import
import com.tencent.wework.api.model.WWAuthMessage;
import com.tencent.wework.api.model.WWMediaLink;
import com.tencent.wework.api.model.WWMediaText;
import com.tencent.wework.api.model.WWMediaImage;

import java.nio.charset.StandardCharsets;

目前正常启动了

**Comment by andfaraway** [comment]
> 我修改了下FlutterWxworkPlugin.java里面的import import com.tencent.wework.api.model.WWAuthMessage; import com.tencent.wework.api.model.WWMediaLink; import com.tencent.wework.api.model.WWMediaText; import com.tencent.wework.api.model.WWMediaImage;
> 
> import java.nio.charset.StandardCharsets;
> 
> 目前正常启动了

好的,因为从上家公司离职了,没有账号无法调试,就很久没更新了,会有一些问题  抱歉~

**Comment by almightyYantao** [comment]
感谢大佬，不过目前还是有点问题，一直都提示没有安装企业微信。我用IOS真机模拟的，我在瞅瞅～

**Comment by andfaraway** [comment]
> 感谢大佬，不过目前还是有点问题，一直都提示没有安装企业微信。我用IOS真机模拟的，我在瞅瞅～

直接用真机调试吧

**Comment by almightyYantao** [comment]
老哥，不知道是否有时间可以求助，加你QQ了～

**Comment by andfaraway** [comment]
感谢~问题已经修复,更新版本0.0.5
