### ISSUE TITLE
  flutter_wxwork: 0.0.6构建报错

### ISSUE THREAD

**Issue by zhangwenxia** [andfaraway/flutter_wxwork#12]
flutter版本是3.24.2

运行 flutter run 时，报如下错误
A problem occurred configuring project ':flutter_wxwork'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by andfaraway** [comment]
> flutter版本是3.24.2
> 
> 运行 flutter run 时，报如下错误 A problem occurred configuring project ':flutter_wxwork'.
> 
> > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
> > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
> 
> ```
>  If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
> ```
是直接运行demo吗,flutter doctor发一下

**Comment by zhangwenxia** [comment]
> > flutter版本是3.24.2
> > 运行 flutter run 时，报如下错误 A problem occurred configuring project ':flutter_wxwork'.
> > > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
> > > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
> > 
> > 
> > ```
> >  If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
> > ```
> 
> 是直接运行demo吗,flutter doctor发一下

[✓] Flutter (Channel stable, 3.24.2, on macOS 13.6.5 22G621 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] VS Code (version 1.93.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
是当前的一个项目需要使用到企业微信分享，目前只是把依赖插件引入进来

**Comment by andfaraway** [comment]
```
flutter_wxwork:
    git:
      url: https://github.com/andfaraway/flutter_wxwork.git
      ref: "flag1"
```

引用改成这个试下,还有这个库是不支持模拟器的

**Comment by zhangwenxia** [comment]
> ```
> flutter_wxwork:
>     git:
>       url: https://github.com/andfaraway/flutter_wxwork.git
>       ref: "flag1"
> ```
> 
> 引用改成这个试下,还有这个库是不支持模拟器的

你好，按照你发给我引用地址，运行后还是报错：
Incorrect package="com.example.flutter_wxwork" found in source AndroidManifest.xml: /Users/zhangwenxia/.pub-cache/git/flutter_wxwork-38253684b6b75d342e01125f6aafafd2c795df30/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.example.flutter_wxwork" from the source AndroidManifest.xml: /Users/zhangwenxia/.pub-cache/git/flutter_wxwork-38253684b6b75d342e01125f6aafafd2c795df30/android/src/main/AndroidManifest.xml.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_wxwork:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.example.flutter_wxwork" found in source AndroidManifest.xml: /Users/zhangwenxia/.pub-cache/git/flutter_wxwork-38253684b6b75d342e01125f6aafafd2c795df30/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.example.flutter_wxwork" from the source AndroidManifest.xml: /Users/zhangwenxia/.pub-cache/git/flutter_wxwork-38253684b6b75d342e01125f6aafafd2c795df30/android/src/main/AndroidManifest.xml.

**Comment by andfaraway** [comment]
```
flutter_wxwork:
    git:
      url: https://github.com/andfaraway/flutter_wxwork.git
      ref: "flag2"
```

抱歉,由于我这边没有复现,只能尝试改下, 再麻烦你再切换分支试下,如果可以的话你提供一个复现demo给我

**Comment by zhangwenxia** [comment]
> ```
> flutter_wxwork:
>     git:
>       url: https://github.com/andfaraway/flutter_wxwork.git
>       ref: "flag2"
> ```
> 
> 抱歉,由于我这边没有复现,只能尝试改下, 再麻烦你再切换分支试下,如果可以的话你提供一个复现demo给我

非常感谢，已经可以了，我用的不是demo开发的，出现这个报错我仅仅只是在pubspec.yaml中添加了依赖，然后运行，就直接报错了，没有写任何业务代码

**Comment by zhangwenxia** [comment]
> ```
> flutter_wxwork:
>     git:
>       url: https://github.com/andfaraway/flutter_wxwork.git
>       ref: "flag2"
> ```
> 
> 抱歉,由于我这边没有复现,只能尝试改下, 再麻烦你再切换分支试下,如果可以的话你提供一个复现demo给我

非常感谢，已经可以了，我用的不是demo开发的，出现这个报错我仅仅只是在pubspec.yaml中添加了依赖，然后运行，就直接报错了，没有写任何业务代码

**Comment by andfaraway** [comment]
感谢,我会合到主分支去,0.0.7,稍晚点发布,你更新依赖就可以
