### ISSUE TITLE
IOS build失败

### ISSUE THREAD

**Issue by AugustWangVeeva** [andfaraway/flutter_wxwork#3]
Showing Recent Messages
Error (Xcode): In /Users/AugWan/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.3/ios/Assets/libWXWorkApi.a(WWKApiObject+WXOnly.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/AugWan/.pub-cache/hosted/pub.dev/flutter_wxwork-0.0.3/ios/Assets/libWXWorkApi.a' for architecture arm64

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

**Comment by andfaraway** [comment]
sdk不支持模拟器，需要使用真机

**Comment by AugustWangVeeva** [comment]
能否支持至少build过去

**Comment by AugustWangVeeva** [comment]
因为大部分功能基本都是在simulator去开发，这个build不过去影响其他功能，只是登录功能需要真机，所以能否至少支持一下能够模拟器能够build过去？

**Comment by andfaraway** [comment]
> 因为大部分功能基本都是在simulator去开发，这个build不过去影响其他功能，只是登录功能需要真机，所以能否至少支持一下能够模拟器能够build过去？

腾讯sdk没有支持，没法。

**Comment by AugustWangVeeva** [comment]
@andfaraway 这个https://github.com/lichfy/fluwx_worker 也是企业微信登录的，只不过是没有再继续支持null safety，这个应该也用到了腾讯sdk，就能build过去，能在模拟器使用，不能参考下吗

**Comment by andfaraway** [comment]
> @andfaraway 这个https://github.com/lichfy/fluwx_worker 也是企业微信登录的，只不过是没有再继续支持null safety，这个应该也用到了腾讯sdk，就能build过去，能在模拟器使用，不能参考下吗

等腾讯更新sdk支持模拟器后就可以了。
