### ISSUE TITLE
android 拉起失败

### ISSUE THREAD

**Issue by CZ2019518** [andfaraway/flutter_wxwork#4]
Uploading 621_1718241816.mp4…

**Comment by andfaraway** [comment]
@zhangcheng1989 检查一下几个id对不对,最好用复制的

**Comment by CZ2019518** [comment]
是对的，肯定是复制的，但是为什么会出现这个拦截就搞不懂了

**Comment by andfaraway** [comment]
@zhangcheng1989 
你可以提供一下视频和demo吗
