### ISSUE TITLE
支持分享

### ISSUE THREAD

**Issue by WANGNEWMAN** [andfaraway/flutter_wxwork#5]
Future<AuthModel> auth({String state = 'state'})这方法看起来不支持分享内容，能否再加一下分享内容这个方法？

**Comment by andfaraway** [comment]
> Future auth({String state = 'state'})这方法看起来不支持分享内容，能否再加一下分享内容这个方法？

抱歉近期应该没时间弄,公司业务太繁忙了.

**Comment by WANGNEWMAN** [comment]
Future auth({String state = 'state'})扩展支持把消息映射到对应的message对象就可以了

**Comment by andfaraway** [comment]
最近实在是抽不出时间,感谢推送

**Comment by andfaraway** [comment]
@WANGNEWMAN  pub库已更新至0.0.4
