### ISSUE TITLE
ios拉起企业微信失败

### ISSUE THREAD

**Issue by NEOLEE98** [andfaraway/flutter_wxwork#8]
注册返回true，调用auth时xcode报错以下代码且auth所在函数被直接打断
`BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).`

**Comment by NEOLEE98** [comment]
经实验是因为苹果在iOS18关停了这个接口，并且这个调用由静态库发起，估计只能找tx更新了（但是这个库上次更新在2021）

**Comment by andfaraway** [comment]
等正式版发布后再看吧

**Comment by NEOLEE98** [comment]
正式版确实deprecate了openurl了，正式版也无法调用

**Comment by andfaraway** [comment]
> 正式版确实deprecate了openurl了，正式版也无法调用

刚看了,腾讯sdk没更新,等更新吧
